
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"

extern struct dbg_info* dbg_info__cause_bounds;
#undef MY_TRACE_FLAG
#define MY_TRACE_FLAG _cause_bounds_TRACE
long _cause_bounds_TRACE;
extern struct OPS *int_ops;
static Vlist0 owns__cause_bounds = {0, 0};

/**** BEGIN PROCEDURE _cause_bounds ****/

errcode _cause_bounds()
    {
    struct {
        struct dbg_info *DBG_INFO;
        long DBG_LINE;
        errcode err;
        errcode ecode2;
        } locals;
    locals.DBG_INFO = dbg_info__cause_bounds;
    enter_proc(3);

  LINE(4);
    {
    {signal (ERR_bounds);}}
    goto end_0;
    ex_0:
        {
            if (locals.err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(locals.err);
            {signal(ERR_failure);}
        }
    end_0: {signal(ERR_ok);}
    }

/**** END PROCEDURE _cause_bounds ****/

typedef struct {
    long hdr;
    long count;
    char *name;
    char *fname;
    bool is_iter;
    long is_parmd;
    long addr;
    long nargs;
    Vlist0 *vals;
    siglist1 *sigs;
    Vlist2 *locals;
    Vlist0 *owns;
    Vlist0 *ptowns;
    Vlist0 *popowns;
    Slist0 *type_formals;
    Slist0 *op_formals;
    } dbg_info__cause_bounds_actual;
static Vlist0 vals__cause_bounds = {0, 0};
static sig_desc0 sig__cause_bounds_1 = {0, 3, "bounds", {0, 0
}};
static siglist1 sigs__cause_bounds = {0, 1, (sig_desc*)&sig__cause_bounds_1};
static Vlist2 locals__cause_bounds = {0, 2,{ {0, 2, "err", &int_ops},  {0, 2, "ecode2", &int_ops}}
};
static Vlist0 popowns__cause_bounds = {0, 0};
Slist0 tformals__cause_bounds = {0, 0};
Slist0 opformals__cause_bounds = {0, 0};
dbg_info__cause_bounds_actual dbg_info__cause_bounds_data = {0, 12, 
    "_cause_bounds", "/home/dcurtis/pclu-debian/sys/clu/_cause_bounds.clu", 0, 0, (long)_cause_bounds, 0, 
    &vals__cause_bounds, &sigs__cause_bounds, &locals__cause_bounds, &owns__cause_bounds, &NO_VALS, &NO_VALS, &NO_PARMS, &NO_PARMS};
    struct dbg_info *dbg_info__cause_bounds = (struct dbg_info*)&dbg_info__cause_bounds_data;
