
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


extern struct dbg_info* dbg_info__dir_ent_size;
#undef MY_TRACE_FLAG
#define MY_TRACE_FLAG _dir_ent_size_TRACE
long _dir_ent_size_TRACE;
extern struct OPS *int_ops;
static Vlist1 owns__dir_ent_size = {0, 1,{ {0, 2, "_init", &int_ops}
}
};

/**** BEGIN PROCEDURE _dir_ent_size ****/

errcode _dir_ent_size(ret_1)
CLUREF *ret_1;
    {
    struct {
        struct dbg_info *DBG_INFO;
        long DBG_LINE;
        errcode err;
        errcode ecode2;
        } locals;
    locals.DBG_INFO = dbg_info__dir_ent_size;
    enter_proc(3);

  LINE(4);
    {
    {
    ret_1->num = 255;
    }
    {signal (ERR_ok);}}
    goto end_0;
    ex_0:
        {
            if (locals.err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(locals.err);
            {signal(ERR_failure);}
        }
    end_0: elist[0].str = no_return_values_STRING;
        {signal(ERR_failure);}
    }

/**** END PROCEDURE _dir_ent_size ****/

typedef struct {
    long hdr;
    long count;
    char *name;
    char *fname;
    bool is_iter;
    long is_parmd;
    long addr;
    long nargs;
    Vlist1 *vals;
    siglist0 *sigs;
    Vlist2 *locals;
    Vlist1 *owns;
    Vlist0 *ptowns;
    Vlist0 *popowns;
    Slist0 *type_formals;
    Slist0 *op_formals;
    } dbg_info__dir_ent_size_actual;
static Vlist1 vals__dir_ent_size = {0, 1, { {0, 2, "", &int_ops}}
};
static siglist0 sigs__dir_ent_size = {0, 0};
static Vlist2 locals__dir_ent_size = {0, 2,{ {0, 2, "err", &int_ops},  {0, 2, "ecode2", &int_ops}}
};
static Vlist0 popowns__dir_ent_size = {0, 0};
Slist0 tformals__dir_ent_size = {0, 0};
Slist0 opformals__dir_ent_size = {0, 0};
dbg_info__dir_ent_size_actual dbg_info__dir_ent_size_data = {0, 12, 
    "_dir_ent_size", "/home/dcurtis/pclu-debian/sys/clu/_dir_ent_size.clu", 0, 0, (long)_dir_ent_size, 0, 
    &vals__dir_ent_size, &sigs__dir_ent_size, &locals__dir_ent_size, &owns__dir_ent_size, &NO_VALS, &NO_VALS, &NO_PARMS, &NO_PARMS};
    struct dbg_info *dbg_info__dir_ent_size = (struct dbg_info*)&dbg_info__dir_ent_size_data;
