
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


extern struct dbg_info* dbg_info__fixup_dir_part;
#undef MY_TRACE_FLAG
#define MY_TRACE_FLAG _fixup_dir_part_TRACE
long _fixup_dir_part_TRACE;
extern struct OPS *int_ops;
static Vlist1 owns__fixup_dir_part = {0, 1,{ {0, 2, "_init", &int_ops}
}
};
extern errcode stringOPindexs();
extern errcode intOPequal();
extern errcode stringOPconcat();
extern errcode stringOPsubstr();
extern errcode stringOPrest();
extern errcode intOPadd();
extern errcode stringOPsize();
extern errcode intOPgt();
extern errcode charOPequal();
extern errcode stringOPfetch();
extern errcode intOPsub();
extern OWN_req string_ownreqs;
extern struct OPS *string_ops;
CLUREF STR__057_057;
static int _fixup_dir_part_own_init = 0;

/**** BEGIN PROCEDURE _fixup_dir_part ****/

errcode _fixup_dir_part(s, ret_1)
CLUREF s;
CLUREF *ret_1;
    {
    struct {
        struct dbg_info *DBG_INFO;
        long DBG_LINE;
        errcode err;
        errcode ecode2;
        CLUREF i;
        CLUREF s;
        } locals;
    locals.i.num = UNINIT;
    locals.s.num = UNINIT;
    locals.DBG_INFO = dbg_info__fixup_dir_part;
    locals.s = s;
        if (_fixup_dir_part_own_init == 0) {
        stringOPcons("//", CLU_1, CLU_2, &STR__057_057);
        _fixup_dir_part_own_init = 1;
    }
    enter_proc(3);

  LINE(4);
    for (;;) {
        if (true != true) { break; }

  LINE(5);
        {
            {CLUREF T_2_1;
            locals.err = stringOPindexs(STR__057_057, locals.s, &T_2_1);
            if (locals.err != ERR_ok) goto ex_0;
            locals.i.num = T_2_1.num;
            }
            }

  LINE(6);
        {
        CLUREF T_2_1;
        T_2_1.num = (locals.i.num == 0)? true : false;
        if (T_2_1.num == true) {

  LINE(7);
            goto end_while_1;
            }
            }/* end if */

  LINE(8);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        CLUREF T_2_3;
        CLUREF T_2_4;
        locals.err = stringOPsubstr(locals.s, CLU_1, locals.i, &T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = intOPadd(locals.i, CLU_2, &T_2_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPrest(locals.s, T_2_2, &T_2_3);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPconcat(T_2_1, T_2_3, &T_2_4);
        if (locals.err != ERR_ok) goto ex_0;
        locals.s.num = T_2_4.num;
        }
        }
        end_while_1:;

  LINE(10);
    {
        {CLUREF T_1_1;
        locals.err = stringOPsize(locals.s, &T_1_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.i.num = T_1_1.num;
        }
        }

  LINE(11);
    {
    CLUREF T_1_1;
    CLUREF T_1_2;
    CLUREF T_1_3;
    CLUREF T_1_4;
    CLUREF T_1_5;
    T_1_2.num = (locals.i.num > 1)? true : false;
    T_1_1.num = T_1_2.num;
    if (T_1_2.num) {
        locals.err = stringOPfetch(locals.s, locals.i, &T_1_3);
        if (locals.err != ERR_ok) goto ex_0;
        T_1_4.ch = '/';
        T_1_5.num = (T_1_3.ch == T_1_4.ch)? true : false;
        T_1_1.num = T_1_5.num;
    }
    if (T_1_1.num == true) {

  LINE(12);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        locals.err = intOPsub(locals.i, CLU_1, &T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPsubstr(locals.s, CLU_1, T_2_1, &T_2_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.s.num = T_2_2.num;
        }
        }
        }/* end if */

  LINE(13);
    {
    {
    ret_1->num = locals.s.num;
    }
    {signal (ERR_ok);}}
    goto end_0;
    ex_0:
        {
            if (locals.err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(locals.err);
            {signal(ERR_failure);}
        }
    end_0: elist[0].str = no_return_values_STRING;
        {signal(ERR_failure);}
    }

/**** END PROCEDURE _fixup_dir_part ****/

typedef struct {
    long hdr;
    long count;
    char *name;
    char *fname;
    bool is_iter;
    long is_parmd;
    long addr;
    long nargs;
    Vlist1 *vals;
    siglist0 *sigs;
    Vlist4 *locals;
    Vlist1 *owns;
    Vlist0 *ptowns;
    Vlist0 *popowns;
    Slist0 *type_formals;
    Slist0 *op_formals;
    } dbg_info__fixup_dir_part_actual;
static Vlist1 vals__fixup_dir_part = {0, 1, { {0, 2, "", &string_ops}}
};
static siglist0 sigs__fixup_dir_part = {0, 0};
static Vlist4 locals__fixup_dir_part = {0, 4,{ {0, 2, "err", &int_ops},  {0, 2, "ecode2", &int_ops},  {0, 2, "i", &int_ops},  {0, 2, "s", &string_ops}}
};
static Vlist0 popowns__fixup_dir_part = {0, 0};
Slist0 tformals__fixup_dir_part = {0, 0};
Slist0 opformals__fixup_dir_part = {0, 0};
dbg_info__fixup_dir_part_actual dbg_info__fixup_dir_part_data = {0, 12, 
    "_fixup_dir_part", "/home/dcurtis/pclu-debian/sys/clu/_fixup_dir_part.clu", 0, 0, (long)_fixup_dir_part, 1, 
    &vals__fixup_dir_part, &sigs__fixup_dir_part, &locals__fixup_dir_part, &owns__fixup_dir_part, &NO_VALS, &NO_VALS, &NO_PARMS, &NO_PARMS};
    struct dbg_info *dbg_info__fixup_dir_part = (struct dbg_info*)&dbg_info__fixup_dir_part_data;
