
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


extern struct dbg_info* dbg_info__split_name_part;
#undef MY_TRACE_FLAG
#define MY_TRACE_FLAG _split_name_part_TRACE
long _split_name_part_TRACE;
extern struct OPS *int_ops;
static Vlist1 owns__split_name_part = {0, 1,{ {0, 2, "_init", &int_ops}
}
};
extern errcode stringOPindexc();
extern errcode intOPgt();
extern errcode intOPadd();
extern errcode charOPequal();
extern errcode stringOPfetch();
extern errcode intOPequal();
extern errcode stringOPsubstr();
extern errcode intOPsub();
extern errcode stringOPrest();
extern OWN_req string_ownreqs;
extern struct OPS *string_ops;
CLUREF STR_;
static int _split_name_part_own_init = 0;

/**** BEGIN PROCEDURE _split_name_part ****/

errcode _split_name_part(s, ret_1, ret_2, ret_3)
CLUREF s;
CLUREF *ret_1;
CLUREF *ret_2;
CLUREF *ret_3;
    {
    struct {
        struct dbg_info *DBG_INFO;
        long DBG_LINE;
        errcode err;
        errcode ecode2;
        CLUREF i;
        CLUREF j;
        CLUREF name;
        CLUREF suffix;
        CLUREF s;
        } locals;
    locals.i.num = UNINIT;
    locals.j.num = UNINIT;
    locals.name.num = UNINIT;
    locals.suffix.num = UNINIT;
    locals.s.num = UNINIT;
    locals.DBG_INFO = dbg_info__split_name_part;
    locals.s = s;
        if (_split_name_part_own_init == 0) {
        stringOPcons("", CLU_1, CLU_0, &STR_);
        _split_name_part_own_init = 1;
    }
    enter_proc(3);

  LINE(4);
    {
        {CLUREF T_1_1;
        CLUREF T_1_2;
        T_1_1.ch = '.';
        locals.err = stringOPindexc(T_1_1, locals.s, &T_1_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.i.num = T_1_2.num;
        }
        }

  LINE(5);
    {
    CLUREF T_1_1;
    T_1_1.num = (locals.i.num > 0)? true : false;
    if (T_1_1.num == true) {

  LINE(6);
        {
            {CLUREF T_2_1;
            locals.err = intOPadd(locals.i, CLU_1, &T_2_1);
            if (locals.err != ERR_ok) goto ex_0;
            locals.j.num = T_2_1.num;
            }
            }

  LINE(7);
        for (;;) {
            CLUREF T_3_1;
            CLUREF T_3_2;
            CLUREF T_3_3;
            locals.err = stringOPfetch(locals.s, locals.j, &T_3_1);
            if (locals.err != ERR_ok) goto ex_1;
            T_3_2.ch = '.';
            T_3_3.num = (T_3_1.ch == T_3_2.ch)? true : false;
            if (T_3_3.num != true) { break; }

  LINE(8);
            {
            CLUREF T_4_1;
            locals.err = intOPadd(locals.j, CLU_1, &T_4_1);
            if (locals.err != ERR_ok) goto ex_1;
            locals.j.num = T_4_1.num;
            }
            }
            end_while_1:;
            goto end_1;
            ex_1:
                if ((locals.err == ERR_bounds)) {

  LINE(9);
                    {
                    locals.i.num = 0;
                    }
                }
                else {
                    goto ex_0;
                }
            end_1:;
        }
        }/* end if */

  LINE(11);
    {
    CLUREF T_1_1;
    T_1_1.num = (locals.i.num == 0)? true : false;
    if (T_1_1.num == true) {

  LINE(12);
        {
        {
        ret_1->num = locals.s.num;
        }
        {
        ret_2->str = STR_.str;
        }
        {
        ret_3->str = STR_.str;
        }
        {signal (ERR_ok);}}
        }
        }/* end if */

  LINE(13);
    {
        {CLUREF T_1_1;
        CLUREF T_1_2;
        locals.err = intOPsub(locals.i, CLU_1, &T_1_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPsubstr(locals.s, CLU_1, T_1_1, &T_1_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.name.num = T_1_2.num;
        }
        }

  LINE(14);
    {
        {CLUREF T_1_1;
        CLUREF T_1_2;
        locals.err = intOPadd(locals.i, CLU_1, &T_1_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPrest(locals.s, T_1_1, &T_1_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.suffix.num = T_1_2.num;
        }
        }

  LINE(15);
    {
    CLUREF T_1_1;
    CLUREF T_1_2;
    T_1_1.ch = '.';
    locals.err = stringOPindexc(T_1_1, locals.suffix, &T_1_2);
    if (locals.err != ERR_ok) goto ex_0;
    locals.i.num = T_1_2.num;
    }

  LINE(16);
    {
    CLUREF T_1_1;
    T_1_1.num = (locals.i.num > 0)? true : false;
    if (T_1_1.num == true) {

  LINE(17);
        {
            {CLUREF T_2_1;
            locals.err = intOPadd(locals.i, CLU_1, &T_2_1);
            if (locals.err != ERR_ok) goto ex_0;
            locals.j.num = T_2_1.num;
            }
            }

  LINE(18);
        for (;;) {
            CLUREF T_3_1;
            CLUREF T_3_2;
            CLUREF T_3_3;
            locals.err = stringOPfetch(locals.suffix, locals.j, &T_3_1);
            if (locals.err != ERR_ok) goto ex_2;
            T_3_2.ch = '.';
            T_3_3.num = (T_3_1.ch == T_3_2.ch)? true : false;
            if (T_3_3.num != true) { break; }

  LINE(19);
            {
            CLUREF T_4_1;
            locals.err = intOPadd(locals.j, CLU_1, &T_4_1);
            if (locals.err != ERR_ok) goto ex_2;
            locals.j.num = T_4_1.num;
            }
            }
            end_while_2:;
            goto end_2;
            ex_2:
                if ((locals.err == ERR_bounds)) {

  LINE(20);
                    {
                    locals.i.num = 0;
                    }
                }
                else {
                    goto ex_0;
                }
            end_2:;
        }
        }/* end if */

  LINE(22);
    {
    CLUREF T_1_1;
    T_1_1.num = (locals.i.num == 0)? true : false;
    if (T_1_1.num == true) {

  LINE(23);
        {
        locals.s = STR_;
        }
        }
    else {

  LINE(24);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        locals.err = intOPadd(locals.i, CLU_1, &T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPrest(locals.suffix, T_2_1, &T_2_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.s.num = T_2_2.num;
        }

  LINE(25);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        locals.err = intOPsub(locals.i, CLU_1, &T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPsubstr(locals.suffix, CLU_1, T_2_1, &T_2_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.suffix.num = T_2_2.num;
        }
        }}/* end if */

  LINE(27);
    {
    {
    ret_1->num = locals.name.num;
    }
    {
    ret_2->num = locals.suffix.num;
    }
    {
    ret_3->num = locals.s.num;
    }
    {signal (ERR_ok);}}
    goto end_0;
    ex_0:
        {
            if (locals.err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(locals.err);
            {signal(ERR_failure);}
        }
    end_0: elist[0].str = no_return_values_STRING;
        {signal(ERR_failure);}
    }

/**** END PROCEDURE _split_name_part ****/

typedef struct {
    long hdr;
    long count;
    char *name;
    char *fname;
    bool is_iter;
    long is_parmd;
    long addr;
    long nargs;
    Vlist3 *vals;
    siglist0 *sigs;
    Vlist7 *locals;
    Vlist1 *owns;
    Vlist0 *ptowns;
    Vlist0 *popowns;
    Slist0 *type_formals;
    Slist0 *op_formals;
    } dbg_info__split_name_part_actual;
static Vlist3 vals__split_name_part = {0, 3, { {0, 2, "", &string_ops},  {0, 2, "", &string_ops},  {0, 2, "", &string_ops}}
};
static siglist0 sigs__split_name_part = {0, 0};
static Vlist7 locals__split_name_part = {0, 7,{ {0, 2, "err", &int_ops},  {0, 2, "ecode2", &int_ops},  {0, 2, "i", &int_ops},  {0, 2, "j", &int_ops},  {0, 2, "name", &string_ops},  {0, 2, "suffix", &string_ops},  {0, 2, "s", &string_ops}}
};
static Vlist0 popowns__split_name_part = {0, 0};
Slist0 tformals__split_name_part = {0, 0};
Slist0 opformals__split_name_part = {0, 0};
dbg_info__split_name_part_actual dbg_info__split_name_part_data = {0, 12, 
    "_split_name_part", "/home/dcurtis/pclu-debian/sys/clu/_split_name_part.clu", 0, 0, (long)_split_name_part, 1, 
    &vals__split_name_part, &sigs__split_name_part, &locals__split_name_part, &owns__split_name_part, &NO_VALS, &NO_VALS, &NO_PARMS, &NO_PARMS};
    struct dbg_info *dbg_info__split_name_part = (struct dbg_info*)&dbg_info__split_name_part_data;
