
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


extern struct dbg_info* dbg_info_file_name_fill;
#undef MY_TRACE_FLAG
#define MY_TRACE_FLAG file_name_fill_TRACE
long file_name_fill_TRACE;
extern struct OPS *int_ops;
static Vlist1 owns_file_name_fill = {0, 1,{ {0, 2, "_init", &int_ops}
}
};
extern errcode file_nameOPget_dir();
extern errcode file_nameOPget_suffix();
extern errcode stringOPempty();
extern errcode working_dir();
extern errcode boolOPnot();
extern errcode charOPequal();
extern errcode stringOPfetch();
extern errcode stringOPindexc();
extern errcode intOPequal();
extern errcode intOPadd();
extern errcode stringOPsize();
extern errcode stringOPconcat();
extern errcode _home_dir();
extern errcode stringOPsubstr();
extern errcode intOPsub();
extern errcode stringOPrest();
extern errcode stringOPequal();
extern errcode file_nameOPcreate();
extern errcode file_nameOPget_name();
extern errcode file_nameOPget_other();
extern OWN_req file_name_ownreqs;
extern struct OPS *file_name_ops;
static int file_name_fill_own_init = 0;

/**** BEGIN PROCEDURE file_name_fill ****/

errcode file_name_fill(fn, dsuffix, ret_1)
CLUREF fn;
CLUREF dsuffix;
CLUREF *ret_1;
    {
    struct {
        struct dbg_info *DBG_INFO;
        long DBG_LINE;
        errcode err;
        errcode ecode2;
        CLUREF dir;
        CLUREF suffix;
        CLUREF change;
        CLUREF z;
        CLUREF fn;
        CLUREF dsuffix;
        } locals;
    locals.dir.num = UNINIT;
    locals.suffix.num = UNINIT;
    locals.change.num = UNINIT;
    locals.z.num = UNINIT;
    locals.fn.num = UNINIT;
    locals.dsuffix.num = UNINIT;
    locals.DBG_INFO = dbg_info_file_name_fill;
    locals.fn = fn;
    locals.dsuffix = dsuffix;
        if (file_name_fill_own_init == 0) {
        file_name_fill_own_init = 1;
    }
    enter_proc(3);

  LINE(5);
    {
        {CLUREF T_1_1;
        locals.err = file_nameOPget_dir(locals.fn, &T_1_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.dir.num = T_1_1.num;
        }
        }

  LINE(6);
    {
        {CLUREF T_1_1;
        locals.err = file_nameOPget_suffix(locals.fn, &T_1_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.suffix.num = T_1_1.num;
        }
        }

  LINE(7);
    {
        {locals.change.tf = false;
        }
        }

  LINE(8);
    {
    CLUREF T_1_1;
    locals.err = stringOPempty(locals.dir, &T_1_1);
    if (locals.err != ERR_ok) goto ex_0;
    if (T_1_1.num == true) {

  LINE(9);
        {
        CLUREF T_2_1;
        locals.err = working_dir(&T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.dir.num = T_2_1.num;
        }

  LINE(10);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        locals.err = stringOPempty(locals.dir, &T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        T_2_2.num = T_2_1.num ^ 1;
        locals.change.num = T_2_2.num;
        }
        }
    else {
    CLUREF T_1_2;
    CLUREF T_1_3;
    CLUREF T_1_4;
    locals.err = stringOPfetch(locals.dir, CLU_1, &T_1_2);
    if (locals.err != ERR_ok) goto ex_0;
    T_1_3.ch = '~';
    T_1_4.num = (T_1_2.ch == T_1_3.ch)? true : false;
    if (T_1_4.num == true) {

  LINE(12);
        {
            {CLUREF T_2_1;
            CLUREF T_2_2;
            T_2_1.ch = '/';
            locals.err = stringOPindexc(T_2_1, locals.dir, &T_2_2);
            if (locals.err != ERR_ok) goto ex_0;
            locals.z.num = T_2_2.num;
            }
            }

  LINE(13);
        {
        CLUREF T_2_1;
        T_2_1.num = (locals.z.num == 0)? true : false;
        if (T_2_1.num == true) {

  LINE(14);
            {
            CLUREF T_3_1;
            CLUREF T_3_2;
            locals.err = stringOPsize(locals.dir, &T_3_1);
            if (locals.err != ERR_ok) goto ex_0;
            locals.err = intOPadd(T_3_1, CLU_1, &T_3_2);
            if (locals.err != ERR_ok) goto ex_0;
            locals.z.num = T_3_2.num;
            }
            }
            }/* end if */

  LINE(15);
        {
        CLUREF T_3_1;
        CLUREF T_3_2;
        CLUREF T_3_3;
        CLUREF T_3_4;
        CLUREF T_3_5;
        locals.err = intOPsub(locals.z, CLU_2, &T_3_1);
        if (locals.err != ERR_ok) goto ex_1;
        locals.err = stringOPsubstr(locals.dir, CLU_2, T_3_1, &T_3_2);
        if (locals.err != ERR_ok) goto ex_1;
        locals.err = _home_dir(T_3_2, &T_3_3);
        if (locals.err != ERR_ok) goto ex_1;
        locals.err = stringOPrest(locals.dir, locals.z, &T_3_4);
        if (locals.err != ERR_ok) goto ex_1;
        locals.err = stringOPconcat(T_3_3, T_3_4, &T_3_5);
        if (locals.err != ERR_ok) goto ex_1;
        locals.dir.num = T_3_5.num;
        }
            goto end_1;
            ex_1:
                if ((locals.err == ERR_not_found)) {
                }
                else {
                    goto ex_0;
                }
            end_1:;

  LINE(18);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        CLUREF T_2_3;
        locals.err = file_nameOPget_dir(locals.fn, &T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPequal(locals.dir, T_2_1, &T_2_2);
        if (locals.err != ERR_ok) goto ex_0;
        T_2_3.num = T_2_2.num ^ 1;
        locals.change.num = T_2_3.num;
        }
        }
    else {
    CLUREF T_1_5;
    CLUREF T_1_6;
    CLUREF T_1_7;
    CLUREF T_1_8;
    locals.err = stringOPfetch(locals.dir, CLU_1, &T_1_5);
    if (locals.err != ERR_ok) goto ex_0;
    T_1_6.ch = '/';
    T_1_7.num = (T_1_5.ch == T_1_6.ch)? true : false;
    T_1_8.num = T_1_7.num ^ 1;
    if (T_1_8.num == true) {

  LINE(20);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        locals.err = working_dir(&T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPconcat(T_2_1, locals.dir, &T_2_2);
        if (locals.err != ERR_ok) goto ex_0;
        locals.dir.num = T_2_2.num;
        }

  LINE(21);
        {
        CLUREF T_2_1;
        CLUREF T_2_2;
        CLUREF T_2_3;
        locals.err = file_nameOPget_dir(locals.fn, &T_2_1);
        if (locals.err != ERR_ok) goto ex_0;
        locals.err = stringOPequal(locals.dir, T_2_1, &T_2_2);
        if (locals.err != ERR_ok) goto ex_0;
        T_2_3.num = T_2_2.num ^ 1;
        locals.change.num = T_2_3.num;
        }
        }
        }}}/* end if */

  LINE(23);
    {
    CLUREF T_1_1;
    CLUREF T_1_2;
    CLUREF T_1_3;
    CLUREF T_1_4;
    locals.err = stringOPempty(locals.suffix, &T_1_2);
    if (locals.err != ERR_ok) goto ex_0;
    T_1_1.num = T_1_2.num;
    if (T_1_2.num) {
        locals.err = stringOPempty(locals.dsuffix, &T_1_3);
        if (locals.err != ERR_ok) goto ex_0;
        T_1_4.num = T_1_3.num ^ 1;
        T_1_1.num = T_1_4.num;
    }
    if (T_1_1.num == true) {

  LINE(24);
        {
        locals.suffix.num = locals.dsuffix.num;
        }

  LINE(25);
        {
        locals.change.tf = true;
        }
        }
        }/* end if */

  LINE(27);
    {
    if (locals.change.num == true) {

  LINE(28);
        {
        CLUREF T_3_1;
        CLUREF T_3_2;
        CLUREF T_3_3;
        locals.err = file_nameOPget_name(locals.fn, &T_3_1);
        if (locals.err != ERR_ok) goto ex_2;
        locals.err = file_nameOPget_other(locals.fn, &T_3_2);
        if (locals.err != ERR_ok) goto ex_2;
        locals.err = file_nameOPcreate(locals.dir, T_3_1, locals.suffix, T_3_2, &T_3_3);
        if (locals.err != ERR_ok) goto ex_2;
        locals.fn.num = T_3_3.num;
        }
            goto end_2;
            ex_2:
                if ((locals.err == ERR_bad_format)) {
                }
                else {
                    goto ex_0;
                }
            end_2:;
        }
        }/* end if */

  LINE(31);
    {
    {
    ret_1->num = locals.fn.num;
    }
    {signal (ERR_ok);}}
    goto end_0;
    ex_0:
        {
            if (locals.err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(locals.err);
            {signal(ERR_failure);}
        }
    end_0: elist[0].str = no_return_values_STRING;
        {signal(ERR_failure);}
    }

/**** END PROCEDURE file_name_fill ****/

extern struct OPS *string_ops;
extern struct OPS *bool_ops;
typedef struct {
    long hdr;
    long count;
    char *name;
    char *fname;
    bool is_iter;
    long is_parmd;
    long addr;
    long nargs;
    Vlist1 *vals;
    siglist0 *sigs;
    Vlist8 *locals;
    Vlist1 *owns;
    Vlist0 *ptowns;
    Vlist0 *popowns;
    Slist0 *type_formals;
    Slist0 *op_formals;
    } dbg_info_file_name_fill_actual;
static Vlist1 vals_file_name_fill = {0, 1, { {0, 2, "", &file_name_ops}}
};
static siglist0 sigs_file_name_fill = {0, 0};
static Vlist8 locals_file_name_fill = {0, 8,{ {0, 2, "err", &int_ops},  {0, 2, "ecode2", &int_ops},  {0, 2, "dir", &string_ops},  {0, 2, "suffix", &string_ops},  {0, 2, "change", &bool_ops},  {0, 2, "z", &int_ops},  {0, 2, "fn", &file_name_ops},  {0, 2, "dsuffix", &string_ops}}
};
static Vlist0 popowns_file_name_fill = {0, 0};
Slist0 tformals_file_name_fill = {0, 0};
Slist0 opformals_file_name_fill = {0, 0};
dbg_info_file_name_fill_actual dbg_info_file_name_fill_data = {0, 12, 
    "file_name_fill", "/home/dcurtis/pclu-debian/sys/clu/file_name_fill.clu", 0, 0, (long)file_name_fill, 2, 
    &vals_file_name_fill, &sigs_file_name_fill, &locals_file_name_fill, &owns_file_name_fill, &NO_VALS, &NO_VALS, &NO_PARMS, &NO_PARMS};
    struct dbg_info *dbg_info_file_name_fill = (struct dbg_info*)&dbg_info_file_name_fill_data;
