
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


extern struct dbg_info* dbg_info_set_working_dir;
#undef MY_TRACE_FLAG
#define MY_TRACE_FLAG set_working_dir_TRACE
long set_working_dir_TRACE;
extern struct OPS *int_ops;
static Vlist1 owns_set_working_dir = {0, 1,{ {0, 2, "_init", &int_ops}
}
};
extern errcode _working_dir();

/**** BEGIN PROCEDURE set_working_dir ****/

errcode set_working_dir(s)
CLUREF s;
    {
    struct {
        struct dbg_info *DBG_INFO;
        long DBG_LINE;
        errcode err;
        errcode ecode2;
        CLUREF s;
        } locals;
    locals.s.num = UNINIT;
    locals.DBG_INFO = dbg_info_set_working_dir;
    locals.s = s;
    enter_proc(3);

  LINE(4);
    {
    CLUREF T_2_1;
    locals.err = _working_dir(locals.s, CLU_1, &T_2_1);
    if (locals.err != ERR_ok) goto ex_1;
    }
    goto end_1;
    ex_1:
        if (locals.err == ERR_bad_format) {signal(ERR_bad_format);}
        else {
            goto ex_0;}
    end_1:;
    goto end_0;
    ex_0:
        {
            if (locals.err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(locals.err);
            {signal(ERR_failure);}
        }
    end_0: {signal(ERR_ok);}
    }

/**** END PROCEDURE set_working_dir ****/

extern struct OPS *string_ops;
typedef struct {
    long hdr;
    long count;
    char *name;
    char *fname;
    bool is_iter;
    long is_parmd;
    long addr;
    long nargs;
    Vlist0 *vals;
    siglist1 *sigs;
    Vlist3 *locals;
    Vlist1 *owns;
    Vlist0 *ptowns;
    Vlist0 *popowns;
    Slist0 *type_formals;
    Slist0 *op_formals;
    } dbg_info_set_working_dir_actual;
static Vlist0 vals_set_working_dir = {0, 0};
static sig_desc0 sig_set_working_dir_1 = {0, 3, "bad_format", {0, 0
}};
static siglist1 sigs_set_working_dir = {0, 1, (sig_desc*)&sig_set_working_dir_1};
static Vlist3 locals_set_working_dir = {0, 3,{ {0, 2, "err", &int_ops},  {0, 2, "ecode2", &int_ops},  {0, 2, "s", &string_ops}}
};
static Vlist0 popowns_set_working_dir = {0, 0};
Slist0 tformals_set_working_dir = {0, 0};
Slist0 opformals_set_working_dir = {0, 0};
dbg_info_set_working_dir_actual dbg_info_set_working_dir_data = {0, 12, 
    "set_working_dir", "/home/dcurtis/pclu-debian/sys/clu/set_working_dir.clu", 0, 0, (long)set_working_dir, 1, 
    &vals_set_working_dir, &sigs_set_working_dir, &locals_set_working_dir, &owns_set_working_dir, &NO_VALS, &NO_VALS, &NO_PARMS, &NO_PARMS};
    struct dbg_info *dbg_info_set_working_dir = (struct dbg_info*)&dbg_info_set_working_dir_data;
