
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


extern struct dbg_info* dbg_info_working_dir;
#undef MY_TRACE_FLAG
#define MY_TRACE_FLAG working_dir_TRACE
long working_dir_TRACE;
extern struct OPS *int_ops;
static Vlist1 owns_working_dir = {0, 1,{ {0, 2, "_init", &int_ops}
}
};
extern errcode _working_dir();
CLUREF STR_;
static int working_dir_own_init = 0;

/**** BEGIN PROCEDURE working_dir ****/

errcode working_dir(ret_1)
CLUREF *ret_1;
    {
    struct {
        struct dbg_info *DBG_INFO;
        long DBG_LINE;
        errcode err;
        errcode ecode2;
        } locals;
    locals.DBG_INFO = dbg_info_working_dir;
        if (working_dir_own_init == 0) {
        stringOPcons("", CLU_1, CLU_0, &STR_);
        working_dir_own_init = 1;
    }
    enter_proc(3);

  LINE(4);
    {
    {
    CLUREF T_1_1;
    locals.err = _working_dir(STR_, CLU_0, &T_1_1);
    if (locals.err != ERR_ok) goto ex_0;
    ret_1->num = T_1_1.num;
    }
    {signal (ERR_ok);}}
    goto end_0;
    ex_0:
        {
            if (locals.err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(locals.err);
            {signal(ERR_failure);}
        }
    end_0: elist[0].str = no_return_values_STRING;
        {signal(ERR_failure);}
    }

/**** END PROCEDURE working_dir ****/

extern struct OPS *string_ops;
typedef struct {
    long hdr;
    long count;
    char *name;
    char *fname;
    bool is_iter;
    long is_parmd;
    long addr;
    long nargs;
    Vlist1 *vals;
    siglist0 *sigs;
    Vlist2 *locals;
    Vlist1 *owns;
    Vlist0 *ptowns;
    Vlist0 *popowns;
    Slist0 *type_formals;
    Slist0 *op_formals;
    } dbg_info_working_dir_actual;
static Vlist1 vals_working_dir = {0, 1, { {0, 2, "", &string_ops}}
};
static siglist0 sigs_working_dir = {0, 0};
static Vlist2 locals_working_dir = {0, 2,{ {0, 2, "err", &int_ops},  {0, 2, "ecode2", &int_ops}}
};
static Vlist0 popowns_working_dir = {0, 0};
Slist0 tformals_working_dir = {0, 0};
Slist0 opformals_working_dir = {0, 0};
dbg_info_working_dir_actual dbg_info_working_dir_data = {0, 12, 
    "working_dir", "/home/dcurtis/pclu-debian/sys/clu/working_dir.clu", 0, 0, (long)working_dir, 0, 
    &vals_working_dir, &sigs_working_dir, &locals_working_dir, &owns_working_dir, &NO_VALS, &NO_VALS, &NO_PARMS, &NO_PARMS};
    struct dbg_info *dbg_info_working_dir = (struct dbg_info*)&dbg_info_working_dir_data;
