
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"

extern errcode streamOPprimary_output();
extern errcode streamOPputl();
extern errcode intOPunparse();
extern errcode file_nameOPcreate();
extern errcode gc_dump();
extern errcode gc_read();
extern errcode _exit();
extern struct REQS *gc_dump_of_t_reqs;
extern struct OPS *int_ops;
extern OWN_req gc_dump_ownreqs;
struct OPS *gc_dump_of_int_table;
struct OPS *gc_dump_of_int_ops;
struct OPS *gc_dump_of_int_ops;
OWNPTR gc_dump_of_int_owns;
extern struct REQS *gc_read_of_t_reqs;
extern OWN_req gc_read_ownreqs;
struct OPS *gc_read_of_int_table;
struct OPS *gc_read_of_int_ops;
struct OPS *gc_read_of_int_ops;
OWNPTR gc_read_of_int_owns;
extern struct OPS *string_ops;
struct OPS *gc_dump_of_string_table;
struct OPS *gc_dump_of_string_ops;
struct OPS *gc_dump_of_string_ops;
OWNPTR gc_dump_of_string_owns;
struct OPS *gc_read_of_string_table;
struct OPS *gc_read_of_string_ops;
struct OPS *gc_read_of_string_ops;
OWNPTR gc_read_of_string_owns;
CLUREF STR_Hello_040World_041;
CLUREF STR__056;
CLUREF STR_test_055int;
CLUREF STR_gc;
CLUREF STR_;
CLUREF STR_0123456789;
CLUREF STR_test_055str;
static int start_up_own_init = 0;

/**** BEGIN PROCEDURE start_up ****/

errcode start_up()
    {
    errcode err;
    errcode ecode2;
    CLUREF po;
    CLUREF i;
    CLUREF fni;
    CLUREF ni;
    CLUREF s;
    CLUREF fn;
    CLUREF ns;
        if (start_up_own_init == 0) {
        add_parm_info_type(0, int_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_int_ops));
        add_parm_info_type(0, int_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_int_ops));
        add_parm_info_type(0, string_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_string_ops));
        add_parm_info_type(0, string_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_string_ops));
        stringOPcons("Hello World!", CLU_1, CLU_12, &STR_Hello_040World_041);
        stringOPcons(".", CLU_1, CLU_1, &STR__056);
        stringOPcons("test-int", CLU_1, CLU_8, &STR_test_055int);
        stringOPcons("gc", CLU_1, CLU_2, &STR_gc);
        stringOPcons("", CLU_1, CLU_0, &STR_);
        stringOPcons("0123456789", CLU_1, CLU_10, &STR_0123456789);
        stringOPcons("test-str", CLU_1, CLU_8, &STR_test_055str);
        start_up_own_init = 1;
    }
    enter_proc(1);

  LINE(2);
    {
        {CLUREF T_1_1;
        err = streamOPprimary_output(&T_1_1);
        if (err != ERR_ok) goto ex_0;
        po.num = T_1_1.num;
        }
        }

  LINE(3);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(5);
    {
        {i.num = 42;
        }
        }

  LINE(7);
    {
    CLUREF T_1_1;
    err = intOPunparse(i, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    err = streamOPputl(po, T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(8);
    {
        {CLUREF T_1_1;
        err = file_nameOPcreate(STR__056, STR_test_055int, STR_gc, STR_, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        fni.num = T_1_1.num;
        }
        }

  LINE(9);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_int_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(i, fni, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(10);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(11);
    {
        {CLUREF T_1_1;
        generic_CLU_proc.type_owns = 0;
        generic_CLU_proc.op_owns = (long)gc_read_of_int_ops->op_owns;
        generic_CLU_proc.proc = gc_read;
        CUR_PROC_VAR.proc = &generic_CLU_proc;
        err = gc_read(fni, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        ni.num = T_1_1.num;
        }
        }

  LINE(12);
    {
    CLUREF T_1_1;
    err = intOPunparse(ni, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    err = streamOPputl(po, T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(13);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(15);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(17);
    {
        {s = STR_0123456789;
        }
        }

  LINE(18);
    {
    err = streamOPputl(po, s);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(19);
    {
        {CLUREF T_1_1;
        err = file_nameOPcreate(STR__056, STR_test_055str, STR_gc, STR_, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        fn.num = T_1_1.num;
        }
        }

  LINE(20);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(21);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_string_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(s, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(22);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(23);
    {
        {CLUREF T_1_1;
        generic_CLU_proc.type_owns = 0;
        generic_CLU_proc.op_owns = (long)gc_read_of_string_ops->op_owns;
        generic_CLU_proc.proc = gc_read;
        CUR_PROC_VAR.proc = &generic_CLU_proc;
        err = gc_read(fn, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        ns.num = T_1_1.num;
        }
        }

  LINE(24);
    {
    err = streamOPputl(po, ns);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(25);
    {
    err = _exit(CLU_0);
    if (err != ERR_ok) goto ex_0;
    }
    goto end_0;
    ex_0:
        {
            if (err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(err);
            {signal(ERR_failure);}
        }
    end_0: {signal(ERR_ok);}
    }

/**** END PROCEDURE start_up ****/

