
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"

extern errcode streamOPprimary_output();
extern errcode streamOPputl();
extern errcode file_nameOPcreate();
extern errcode gc_dump();
extern errcode gc_read();
extern errcode _exit();
extern struct REQS *gc_dump_of_t_reqs;
extern struct OPS *string_ops;
extern OWN_req gc_dump_ownreqs;
struct OPS *gc_dump_of_string_table;
struct OPS *gc_dump_of_string_ops;
struct OPS *gc_dump_of_string_ops;
OWNPTR gc_dump_of_string_owns;
extern struct REQS *gc_read_of_t_reqs;
extern OWN_req gc_read_ownreqs;
struct OPS *gc_read_of_string_table;
struct OPS *gc_read_of_string_ops;
struct OPS *gc_read_of_string_ops;
OWNPTR gc_read_of_string_owns;
CLUREF STR_Hello_040World_041;
CLUREF STR_0123456789;
CLUREF STR__056;
CLUREF STR_test;
CLUREF STR_gc;
CLUREF STR_;
static int start_up_own_init = 0;

/**** BEGIN PROCEDURE start_up ****/

errcode start_up()
    {
    errcode err;
    errcode ecode2;
    CLUREF po;
    CLUREF s;
    CLUREF fn;
    CLUREF ns;
        if (start_up_own_init == 0) {
        add_parm_info_type(0, string_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_string_ops));
        add_parm_info_type(0, string_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_string_ops));
        stringOPcons("Hello World!", CLU_1, CLU_12, &STR_Hello_040World_041);
        stringOPcons("0123456789", CLU_1, CLU_10, &STR_0123456789);
        stringOPcons(".", CLU_1, CLU_1, &STR__056);
        stringOPcons("test", CLU_1, CLU_4, &STR_test);
        stringOPcons("gc", CLU_1, CLU_2, &STR_gc);
        stringOPcons("", CLU_1, CLU_0, &STR_);
        start_up_own_init = 1;
    }
    enter_proc(1);

  LINE(2);
    {
        {CLUREF T_1_1;
        err = streamOPprimary_output(&T_1_1);
        if (err != ERR_ok) goto ex_0;
        po.num = T_1_1.num;
        }
        }

  LINE(3);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(4);
    {
        {s = STR_0123456789;
        }
        }

  LINE(5);
    {
    err = streamOPputl(po, s);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(6);
    {
        {CLUREF T_1_1;
        err = file_nameOPcreate(STR__056, STR_test, STR_gc, STR_, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        fn.num = T_1_1.num;
        }
        }

  LINE(7);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(8);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_string_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(s, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(9);
    {
    err = streamOPputl(po, STR_Hello_040World_041);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(10);
    {
        {CLUREF T_1_1;
        generic_CLU_proc.type_owns = 0;
        generic_CLU_proc.op_owns = (long)gc_read_of_string_ops->op_owns;
        generic_CLU_proc.proc = gc_read;
        CUR_PROC_VAR.proc = &generic_CLU_proc;
        err = gc_read(fn, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        ns.num = T_1_1.num;
        }
        }

  LINE(11);
    {
    err = streamOPputl(po, ns);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(12);
    {
    err = _exit(CLU_0);
    if (err != ERR_ok) goto ex_0;
    }
    goto end_0;
    ex_0:
        {
            if (err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(err);
            {signal(ERR_failure);}
        }
    end_0: {signal(ERR_ok);}
    }

/**** END PROCEDURE start_up ****/

